# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodTruckTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodTruckTracker

pod 'SwiftLint'

  target 'FoodTruckTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodTruckTrackerUITests' do
    # Pods for testing
  end

end
